name: sawadmin
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^latest_version
  latlong2: ^latest_version
  stack_trace: 1.11.1  # Aligned with flutter_test
  meta: 1.15.0  # Aligned with flutter_test
  html: ^0.15.4
  assets_audio_player_web: ^3.1.1
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  google_maps_flutter_web: ^0.5.7
  google_maps_flutter: ^2.6.1
  mapbox_gl: ^0.16.0
  flutter_map: ^7.0.2
  latlng: ^2.0.7
  latlong2: ^0.9.1
  flutter_map_location_marker: ^9.1.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  sidebar_with_animation: ^0.0.3
  dialog_kh: ^0.0.3
  app_dialog: ^1.1.0
  font_awesome_flutter: ^10.7.0
  loading_animation_widget: ^1.2.1
  awesome_dialog: ^3.2.1
  charts_flutter: ^0.12.0
  charthub: ^1.0.0
  chart_it: ^0.2.2
  flutter_graph: ^0.0.1
  fl_chart: ^0.45.1
  vertical_barchart: ^2.0.0+2
  image_picker_web: ^4.0.0
  syncfusion_flutter_charts: ^27.1.52
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  firebase_core: ^3.6.0
  photo_view: ^0.15.0
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.3
  animated_snack_bar: ^0.4.0
  collection: ^1.19.0
  flare_flutter: ^3.0.2
  http_parser: ^4.1.0
  image: ^4.2.0
  js: ^0.7.1
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  material_color_utilities: ^0.12.0
  simple_animations: ^5.0.2
  string_scanner: 1.2.0  # Aligned with flutter_test
  vm_service: 14.2.5  # Aligned with flutter_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_api: 0.7.2  # Aligned with flutter_test
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/assets/
    - images/assets/alert.mp3
